# @package task
name: motion_velocity_play

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot:
  name: g1_waist_unlocked
terrain: plane

num_envs: 4
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

input:
  action:
    _target_: JointPosition
    action_scaling:
      .*hip_pitch.*: 0.548
      .*hip_roll.*: 0.351
      .*hip_yaw.*: 0.548
      .*knee.*: 0.351
      waist_yaw_joint: 0.541
      waist_roll_joint: 0.439
      waist_pitch_joint: 0.439
      .*ankle.*: 0.439
      .*shoulder.*: 0.173
      .*elbow_joint: 0.173
    max_delay: 2
    alpha_range: [0.8, 1.0]

command:
  _target_: Twist
  linvel_x_range: [-0.6, 1.0]
  linvel_y_range: [-0.5, 0.5]
  angvel_range: [-1.0, 1.0]
  yaw_stiffness_range: [0.0, 0.0]
  use_stiffness_ratio: 0.0
  stand_prob: 0.0
  curriculum: false
  teleop: true

observation:
  student:
    student_command: {}
    joint_pos_multistep: {steps: 4, interval: 1}
    joint_vel_multistep: {steps: 4, interval: 1}
    prev_actions: {steps: 4}
    gravity_multistep: {steps: 4, interval: 1}

reward:
  velocity:
    linvel_exp: {weight: 1.0, dim: 2}
    angvel_z_exp: {weight: 1.0}

randomization: {}

termination:
  max_episode_length: {}
  crash:
    body_names_expr:
    - "pelvis"
    - "torso_link"
    - ".*_hip_.*_link"
    - ".*shoulder_.*_link"
    - ".*(wrist|elbow).*"
  fall_over: {xy_thres: 0.9}
