# @package task
name: motion_tracking

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot: 
  name: g1_waist_unlocked_beyondmimic
terrain: plane

# common
num_envs: 1
max_episode_length: 500

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

input:
  action:
    _target_: JointPosition
    action_scaling: 
      .*hip_pitch.*: 0.547546465
      .*hip_roll.*: 0.350661466
      .*hip_yaw.*: 0.547546465
      .*knee.*: 0.350661466
      waist_yaw_joint: 0.547546465
      waist_roll_joint: 0.438577314
      waist_pitch_joint: 0.438577314
      .*ankle.*: 0.438577314
      .*shoulder.*: 0.438577314
      .*elbow_joint: 0.438577314
      .*wrist_roll.*: 0.438577314
      .*wrist_pitch.*: 0.074500870
      .*wrist_yaw.*: 0.074500870
    max_delay: 0
    alpha_range: [1.0, 1.0]

command:
  _target_: motion_tracking.MotionTrackingCommand
  data_path: walk
  motion_id: null
  future_steps: [0]
  anchor_body_name: torso_link
  single_step_command: true
  resample_motion_on_end: true
  random_start: true
  adaptive_sampling: true
  adaptive_bin_seconds: 1.0
  adaptive_kernel_size: 1
  adaptive_lambda: 0.8
  adaptive_uniform_ratio: 0.1
  adaptive_alpha: 0.001
  reset_pose_range:
    x: [-0.05, 0.05]
    y: [-0.05, 0.05]
    z: [-0.01, 0.01]
    roll: [-0.1, 0.1]
    pitch: [-0.1, 0.1]
    yaw: [-0.2, 0.2]
  reset_velocity_range:
    x: [-0.5, 0.5]
    y: [-0.5, 0.5]
    z: [-0.2, 0.2]
    roll: [-0.52, 0.52]
    pitch: [-0.52, 0.52]
    yaw: [-0.78, 0.78]
  reset_joint_position_range: [-0.1, 0.1]

observation:
  policy:
    command: {}
    motion_anchor_pos_b: {noise_amplitude: 0.25}
    motion_anchor_ori_b: {noise_amplitude: 0.05}
    root_lin_vel_b: {noise_amplitude: 0.5}
    root_ang_vel_b: {noise_amplitude: 0.2}
    joint_pos_bm: {noise_amplitude: 0.01}
    joint_vel_bm: {noise_amplitude: 0.5}
    last_action_bm: {}
  priv:
    command: {}
    motion_anchor_pos_b: {}
    motion_anchor_ori_b: {}
    root_lin_vel_b: {}
    root_ang_vel_b: {}
    joint_pos_bm: {}
    joint_vel_bm: {}
    last_action_bm: {}
    body_pose_b:
      _target_: body_pose_bm
      body_names:
      - "pelvis"
      - "left_hip_roll_link"
      - "left_knee_link"
      - "left_ankle_roll_link"
      - "right_hip_roll_link"
      - "right_knee_link"
      - "right_ankle_roll_link"
      - "torso_link"
      - "left_shoulder_roll_link"
      - "left_elbow_link"
      - "left_wrist_yaw_link"
      - "right_shoulder_roll_link"
      - "right_elbow_link"
      - "right_wrist_yaw_link"
      anchor_body_name: "torso_link"

reward:
  tracking:
    body_pos_tracking:
      weight: 1.0
      body_names: &tracking_keypoints
      - "pelvis"
      - "left_hip_roll_link"
      - "left_knee_link"
      - "left_ankle_roll_link"
      - "right_hip_roll_link"
      - "right_knee_link"
      - "right_ankle_roll_link"
      - "torso_link"
      - "left_shoulder_roll_link"
      - "left_elbow_link"
      - "left_wrist_yaw_link"
      - "right_shoulder_roll_link"
      - "right_elbow_link"
      - "right_wrist_yaw_link"
    body_rotmat_tracking:
      weight: 1.0
      body_names: *tracking_keypoints
    body_lin_vel_tracking:
      weight: 1.0
      body_names: *tracking_keypoints
    body_ang_vel_tracking:
      weight: 1.0
      body_names: *tracking_keypoints
    root_pos_tracking:
      weight: 0.5
    root_quat_tracking:
      weight: 0.5

  regularization:
    action_rate_l2:      {weight: 0.1}
    joint_limits:        {weight: 10.0, joint_names: ".*", offset: 0.0}
    undesired_self_contacts:
      weight: 0.1
      threshold: 1.0
      body_names: "^(?!left_ankle_roll_link$)(?!right_ankle_roll_link$)(?!left_wrist_yaw_link$)(?!right_wrist_yaw_link$).+$"

randomization:
  perturb_body_materials:
    body_names: ".*"
    static_friction_range: [0.3, 1.6]
    dynamic_friction_range: [0.3, 1.2]
    restitution_range: [0.0, 0.5]
  default_joint_pos:
    _target_: motion_tracking.randomize_default_joint_pos
    low: -0.01
    high: 0.01
  torso_com:
    _target_: perturb_body_com
    body_names: "torso_link"
    x: [-0.025, 0.025]
    y: [-0.05, 0.05]
    z: [-0.05, 0.05]
  push_robot:
    _target_: perturb_root_vel
    min_s: 1.0
    max_s: 3.0
    x: [-0.5, 0.5]
    y: [-0.5, 0.5]
    z: [-0.2, 0.2]
    roll: [-0.52, 0.52]
    pitch: [-0.52, 0.52]
    yaw: [-0.78, 0.78]

termination:
  max_episode_length: {}
  anchor_pos_z_error:
    threshold: 0.25
  anchor_ori_error:
    _target_: anchor_projected_gravity_error
    threshold: 0.8
  body_pos_z_error:
    threshold: 0.25
    body_names:
    - "left_ankle_roll_link"
    - "right_ankle_roll_link"
    - "left_wrist_yaw_link"
    - "right_wrist_yaw_link"
